<template>
  <div class="home">
    <table>
      <div class="hyou">
        <tr>
          <td>日付</td>
          <td>2/1</td>
          <td>2/2</td>
          <td>2/3</td>
          <td>2/4</td>
          <td>2/5</td>
          <td>2/6</td>
          <td>2/7</td>
          <td>2/8</td>
          <td>2/9</td>
          <td>2/10</td>
          <td>2/11</td>
          <td>2/12</td>
          <td>2/13</td>
          <td>2/14</td>
          <td>2/15</td>
          <td>2/16</td>
          <td>2/17</td>
          <td>2/18</td>
          <td>2/19</td>
          <td>2/20</td>
          <td>2/21</td>
          <td>2/22</td>
          <td>2/23</td>
          <td>2/24</td>
          <td>2/25</td>
        </tr>
        <tr>
          <td>大宮</td>
          <td>12-18</td>
          <td>休</td>
          <td>休</td>
          <td>10-15</td>
          <td>12-14</td>
          <td>12-18</td>
          <td>16-23</td>
          <td>休</td>
          <td>11-15</td>
          <td>17-22</td>
          <td>12-18</td>
          <td>休</td>
          <td>休</td>
          <td>14-19</td>
          <td>12-20</td>
          <td>16-23</td>
          <td>休</td>
          <td>12-18</td>
          <td>12-18</td>
          <td>休</td>
          <td>10-18</td>
          <td>12-18</td>
          <td>休</td>
          <td>10-18</td>
          <td>10-18</td>
        </tr>
        <tr>
          <td>上野</td>
          <td>12-21</td>
          <td>11-18</td>
          <td>休</td>
          <td>休</td>
          <td>10-18</td>
          <td>10-18</td>
          <td>10-18</td>
          <td>休</td>
          <td>16-22</td>
          <td>11-18</td>
          <td>10-18</td>
          <td>休</td>
          <td>休</td>
          <td>17-22</td>
          <td>18-23</td>
          <td>11-21</td>
          <td>11-20</td>
          <td>休</td>
          <td>休</td>
          <td>10-18</td>
          <td>16-21</td>
          <td>休</td>
          <td>15-20</td>
          <td>12-19</td>
          <td>11-19</td>
        </tr>
        <tr>
          <td>伊藤</td>
          <td>休</td>
          <td>休</td>
          <td>休</td>
          <td>休</td>
          <td>休</td>
          <td>11-21</td>
          <td>11-19</td>
          <td>12-18</td>
          <td>14-20</td>
          <td>11-20</td>
          <td>休</td>
          <td>休</td>
          <td>9-14</td>
          <td>11-18</td>
          <td>11-17</td>
          <td>休</td>
          <td>9-16</td>
          <td>15-21</td>
          <td>13-19</td>
          <td>休</td>
          <td>15-19</td>
          <td>12-18</td>
          <td>休</td>
          <td>休</td>
          <td>休</td>
        </tr>
        <tr>
          <td>加藤</td>
          <td>休</td>
          <td>17-21</td>
          <td>17-21</td>
          <td>休</td>
          <td>18-21</td>
          <td>休</td>
          <td>17-21</td>
          <td>休</td>
          <td>18-21</td>
          <td>17-21</td>
          <td>休</td>
          <td>18-21</td>
          <td>休</td>
          <td>18-21</td>
          <td>休</td>
          <td>17-21</td>
          <td>18-21</td>
          <td>18-21</td>
          <td>休</td>
          <td>休</td>
          <td>17-21</td>
          <td>18-21</td>
          <td>休</td>
          <td>17-21</td>
          <td>17-21</td>
        </tr>
        <tr>
          <td>宇都宮</td>
          <td>休</td>
          <td>休</td>
          <td>17-21</td>
          <td>休</td>
          <td>休</td>
          <td>休</td>
          <td>休</td>
          <td>休</td>
          <td>休</td>
          <td>18-21</td>
          <td>休</td>
          <td>18-21</td>
          <td>休</td>
          <td>休</td>
          <td>休</td>
          <td>17-21</td>
          <td>休</td>
          <td>休</td>
          <td>18-21</td>
          <td>休</td>
          <td>休</td>
          <td>休</td>
          <td>休</td>
          <td>17-20</td>
          <td>休</td>
        </tr>
        <tr>
          <td>村井</td>
          <td>休</td>
          <td>休</td>
          <td>休</td>
          <td>休</td>
          <td>16-21</td>
          <td>休</td>
          <td>休</td>
          <td>休</td>
          <td>休</td>
          <td>17-21</td>
          <td>休</td>
          <td>休</td>
          <td>休</td>
          <td>休</td>
          <td>15-19</td>
          <td>休</td>
          <td>休</td>
          <td>休</td>
          <td>休</td>
          <td>16-21</td>
          <td>休</td>
          <td>休</td>
          <td>休</td>
          <td>休</td>
        </tr>
        <tr>
          <td>英樹</td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
        </tr>
        <tr>
          <td>黒川</td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
        </tr>
        <tr>
          <td>赤井</td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
        </tr>
        <tr>
          <td>小峠</td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
        </tr>
      </div>
    </table>
  </div>
</template>
<script>
export default {
  layout: 'group',
}
</script>
<style scoped>
table {
  border-collapse: collapse;
}
td {
  border: solid 1px;
  padding: 1.5em;
}
</style>
